// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCG3xEl-DZLBJCr-Pcw4U7ijkPxP_mAq4',
    appId: '1:541255520514:web:4ccf36e26048b00df6b21b',
    messagingSenderId: '541255520514',
    projectId: 'smart-fish-feeder-pro-y1s1mtr7',
    authDomain: 'smart-fish-feeder-pro-y1s1mtr7.firebaseapp.com',
    databaseURL: 'https://smart-fish-feeder-pro-y1s1mtr7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-fish-feeder-pro-y1s1mtr7.firebasestorage.app',
    measurementId: 'G-LMS697SNXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADPE5nc5Ug9l7f8ZAIKnzrmjWtff2QeDA',
    appId: '1:541255520514:android:1a58c49053a5ba63f6b21b',
    messagingSenderId: '541255520514',
    projectId: 'smart-fish-feeder-pro-y1s1mtr7',
    databaseURL: 'https://smart-fish-feeder-pro-y1s1mtr7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-fish-feeder-pro-y1s1mtr7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB68mcTUMennzrjGPUVRQuLW3Hse0WMAs',
    appId: '1:541255520514:ios:ddc563288367bc79f6b21b',
    messagingSenderId: '541255520514',
    projectId: 'smart-fish-feeder-pro-y1s1mtr7',
    databaseURL: 'https://smart-fish-feeder-pro-y1s1mtr7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-fish-feeder-pro-y1s1mtr7.firebasestorage.app',
    iosBundleId: 'com.y1s1mtr7.smartfishfeeder.smartFishFeederPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB68mcTUMennzrjGPUVRQuLW3Hse0WMAs',
    appId: '1:541255520514:ios:ddc563288367bc79f6b21b',
    messagingSenderId: '541255520514',
    projectId: 'smart-fish-feeder-pro-y1s1mtr7',
    databaseURL: 'https://smart-fish-feeder-pro-y1s1mtr7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-fish-feeder-pro-y1s1mtr7.firebasestorage.app',
    iosBundleId: 'com.y1s1mtr7.smartfishfeeder.smartFishFeederPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCG3xEl-DZLBJCr-Pcw4U7ijkPxP_mAq4',
    appId: '1:541255520514:web:3f8c85e3e70ee283f6b21b',
    messagingSenderId: '541255520514',
    projectId: 'smart-fish-feeder-pro-y1s1mtr7',
    authDomain: 'smart-fish-feeder-pro-y1s1mtr7.firebaseapp.com',
    databaseURL: 'https://smart-fish-feeder-pro-y1s1mtr7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-fish-feeder-pro-y1s1mtr7.firebasestorage.app',
    measurementId: 'G-1711D1H8LM',
  );
}
